[colors]
draw_bold_text_with_bright_colors = true

# Default colors
[colors.primary]
background = '#100f0f'
foreground = '#fffcf0'
dim_foreground = '#FFFCF0'
bright_foreground = '#FFFCF0'

# Normal colors
[colors.normal]
black   = '#100f0f'
red     = '#af3029'
green   = '#66800b'
yellow  = '#ad8301'
blue    = '#205ea6'
magenta = '#a02f6f'
cyan    = '#24837b'
white   = '#fffcf0'

# Bright colors
[colors.bright]
black   = '#100f0f'
red     = '#d14d41'
green   = '#879a39'
yellow  = '#d0a215'
blue    = '#4385be'
magenta = '#ce5d97'
cyan    = '#3aa99f'
white   = '#fffcf0'
[cursor]
unfocused_hollow = false
thickness = 0.4
blink_interval = 500

[cursor.style]
shape = "Beam"
blinking = "Always"

[debug]
persistent_logging = true

[font]
size = 14

[font.bold]
family = "Iosevka Term NFM"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Iosevka Term NFM"
style = "Italic"

[font.normal]
family = "Iosevka Term NFM"
style = "Normal"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 5000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false
dynamic_title = true

[window.padding]
x = 15
y = 10
